# Generated by Django 3.2 on 2023-04-21 15:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cats', '0002_auto_20230421_1906'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cat',
            old_name='ovner',
            new_name='owner',
        ),
    ]
